kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: neredera/teslafi-exporter
    tags:
      - latest
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
